version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
steps:
  - type: Command
    name: "Calculating MD5 Hash"
    timeoutInSeconds: 10000
    command: |
      echo Welcome | md5sum
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 hash failed"
        timeoutInSeconds: 1000
        runAs: root
outputArtifacts:
  - name: hello_world_image
    type: DOCKER_IMAGE
    location: hello-world:1.0
