version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
steps:
  - type: Command
    name: "Build Hello World"
    timeoutInSeconds: 10000
    command: |
     echo step1 printing
     echo step1 printing again
     git checkout poc1
     git diff --name-only master...poc1
