version: 0.1
component: build
timeoutInSeconds: 1200
runAs: root
shell: bash

steps:
  - type: Command
    name: "Build Hello World"
    timeoutInSeconds: 600
    command: |
      cd src/com/sample/
      javac HelloWorld.java
    onFailure:
      - type: Command
        timeoutInSeconds: 600
        runAs: root
        command: |
          echo "Building Hello World failed"
  - type: Command
      timeoutInSeconds: 600
      name: "Create Docker image"
      command: |
        docker build -t hello-world:1.0 .
      onFailure:
        - type: Command
          timeoutInSeconds: 600
          runAs: root
          command: |
            echo "Creating Docker image failed"

outputArtifacts:
  - name: hello_world_image
    type: DOCKER_IMAGE
    location: hello-world:1.0