version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
steps:
  - type: Command
    name: "Build Hello World"
    timeoutInSeconds: 400
    command: |
      cd src/com/example/
      javac HelloWorld.java
#    onFailure:
#      - type: Command
#        command: |
#          echo "Handling Failure"
#          echo "Failure successfully handled"
#        timeoutInSeconds: 400
#        runAs: root
  - type: Command
    timeoutInSeconds: 400
    name: "Dockerizer & Test"
    command: |
      docker build -t hello-test:1.0 .
#    onFailure:
#      - type: Command
#        command: |
#          echo "Handling Failure"
#          echo "Failure successfully handled"
#        timeoutInSeconds: 400
#        runAs: root
outputArtifacts:
  - name: hello_dev_image
    type: DOCKER_IMAGE
    location: hello-test:1.0